# Generated by Django 5.2.6 on 2025-10-23 20:30

import apps.core.helpers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='img/muscle_groups/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'muscle group',
                'verbose_name_plural': 'muscle groups',
                'db_table': 'muscle_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscles', to='exercises.musclegroup', verbose_name='muscle group')),
            ],
            options={
                'verbose_name': 'muscle',
                'verbose_name_plural': 'muscles',
                'db_table': 'muscle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscle_parts', to='exercises.muscle', verbose_name='muscle')),
            ],
            options={
                'verbose_name': 'muscle part',
                'verbose_name_plural': 'muscle parts',
                'db_table': 'muscle_part',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='img/exercises/', verbose_name='image')),
                ('workout_type', models.CharField(choices=[('calisthenics', 'Calisthenics'), ('gym', 'Gym')], max_length=20, verbose_name='workout type')),
                ('created_by', models.ForeignKey(on_delete=models.SET(apps.core.helpers.get_deleted_user), related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.core.helpers.get_deleted_user), related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('muscle_part', models.ManyToManyField(related_name='exercises', to='exercises.musclepart', verbose_name='muscle part')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'db_table': 'exercise',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='musclepart',
            constraint=models.UniqueConstraint(fields=('muscle', 'name'), name='unique_together_muscle_name'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_by__isnull', True)), fields=('name',), name='unique_exercise_name_if_not_deleted'),
        ),
    ]
